@echo off
title India Transition Lab — Starting Services...
echo Starting India Transition Lab (5 Backends + Next.js Frontend)...
powershell -ExecutionPolicy Bypass -File "%~dp0start_all.ps1" -KillFirst
pause
